spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
  config:
    # 当且仅当 prod 环境下，才从 Nacos 中加载配置
    activate:
      on-profile: prod
    # import 机制，配置在后面的配置优先级高
    import:
      - nacos:msia?refresh=true&group=DEFAULT_GROUP
      - nacos:msia-gateway?refresh=true&group=DEFAULT_GROUP
