@startuml
UNPAID --> UNPAID : MODIFY_ORDER
UNPAID --> PAYING : PAY_ORDER
UNPAID --> CANCEL : CANCEL_ORDER
CANCEL --> DELETED : DELETE_ORDER
UNPAID --> DELETED : DELETE_ORDER
PAYING --> OUT_OF_STOCK : ORDER_OUT_OF_STOCK
OUT_OF_STOCK --> CANCEL : CANCEL_ORDER
OUT_OF_STOCK --> DELETED : DELETE_ORDER
PAYING --> PAID : PAY_ORDER_CONFIRMED
PAID --> DELIVERED : DELIVER_ORDER
DELIVERED --> RETURNED : RETURN_ORDER
DELIVERED --> RECEIVED : RECEIVED_ORDER
RECEIVED --> RETURNED : RETURN_ORDER
RETURNED --> RETURNED_REFUND : REFUND_ORDER
@enduml